# generated by datamodel-codegen:
#   filename:  openapi.json

from __future__ import annotations

from datetime import date
from enum import Enum
from typing import Any

from pydantic import BaseModel, Field, conint, constr


class CategoryEntry(BaseModel):
    description: str | None = Field(None, title='Description')
    level: conint(ge=1, le=3) = Field(..., title='Level')
    name: str = Field(..., title='Name')
    parent_slug: str | None = Field(None, title='Parent Slug')
    slug: str = Field(..., title='Slug')


class CoverageRetailer(BaseModel):
    last_updated_at: str | None = Field(None, title='Last Updated At')
    name: str = Field(..., title='Name')
    products: conint(ge=0) = Field(..., title='Products')
    slug: constr(pattern=r'^[A-Za-z0-9_-]+$', max_length=128) = Field(..., title='Slug')


class ErrorDetail(BaseModel):
    code: str = Field(
        ..., description='Stable token to branch on (never the message).', title='Code'
    )
    details: Any = Field(
        None, description='Field-level errors; present on 422 only.', title='Details'
    )
    message: str = Field(
        ..., description='Human-readable; may change.', title='Message'
    )


class ErrorEnvelope(BaseModel):
    error: ErrorDetail


class FacetValueCount(BaseModel):
    count: int = Field(..., title='Count')
    value: str = Field(..., title='Value')


class MeResponse(BaseModel):
    credits_remaining: int = Field(..., title='Credits Remaining')
    email: str = Field(..., title='Email')
    monthly_credit_cap: int = Field(..., title='Monthly Credit Cap')
    name: str = Field(..., title='Name')
    window_resets_at: str | None = Field(None, title='Window Resets At')


class PriceHistoryResponse(BaseModel):
    avg_price: float | None = Field(None, title='Avg Price')
    brand: str | None = Field(None, title='Brand')
    change: float | None = Field(None, title='Change')
    change_pct: float | None = Field(None, title='Change Pct')
    currency: str | None = Field(None, title='Currency')
    first_observed_at: str | None = Field(None, title='First Observed At')
    first_price: float | None = Field(None, title='First Price')
    from_date: date = Field(..., title='From Date')
    id: str = Field(..., title='Id')
    last_observed_at: str | None = Field(None, title='Last Observed At')
    last_price: float | None = Field(None, title='Last Price')
    max_price: float | None = Field(None, title='Max Price')
    min_price: float | None = Field(None, title='Min Price')
    name: str = Field(..., title='Name')
    observation_count: int = Field(..., title='Observation Count')
    retailer_slug: str = Field(..., title='Retailer Slug')
    store_count: int | None = Field(None, title='Store Count')
    to_date: date = Field(..., title='To Date')


class PriceObservation(BaseModel):
    currency: str = Field(..., title='Currency')
    observed_at: str = Field(..., title='Observed At')
    price: float = Field(..., title='Price')
    store_city: str | None = Field(None, title='Store City')
    store_id: str = Field(..., title='Store Id')
    store_name: str | None = Field(None, title='Store Name')
    unit_price: float | None = Field(None, title='Unit Price')
    unit_price_uom: str | None = Field(None, title='Unit Price Uom')


class PriceObservationsResponse(BaseModel):
    brand: str | None = Field(None, title='Brand')
    found: int = Field(..., title='Found')
    from_date: date = Field(..., title='From Date')
    id: str = Field(..., title='Id')
    name: str = Field(..., title='Name')
    observations: list[PriceObservation] = Field(..., title='Observations')
    page: int = Field(..., title='Page')
    page_size: int = Field(..., title='Page Size')
    retailer_slug: str = Field(..., title='Retailer Slug')
    to_date: date = Field(..., title='To Date')


class SearchHit(BaseModel):
    brand: str | None = Field(None, title='Brand')
    category_path: list[str] | None = Field([], title='Category Path')
    category_slug: str | None = Field(None, title='Category Slug')
    chain_slug: str | None = Field(None, title='Chain Slug')
    country_code: str = Field(..., title='Country Code')
    currency: str | None = Field(None, title='Currency')
    id: str = Field(..., title='Id')
    image_url: str | None = Field(None, title='Image Url')
    latest_observed_at: str | None = Field(None, title='Latest Observed At')
    latest_price: float | None = Field(None, title='Latest Price')
    latest_unit_price: float | None = Field(None, title='Latest Unit Price')
    latest_unit_price_uom: str | None = Field(None, title='Latest Unit Price Uom')
    name: str = Field(..., title='Name')
    quantity_unit: str | None = Field(None, title='Quantity Unit')
    quantity_value: float | None = Field(None, title='Quantity Value')
    retailer_slug: str = Field(..., title='Retailer Slug')
    store_cities: list[str] | None = Field([], title='Store Cities')
    tags: list[str] | None = Field([], title='Tags')
    url: str | None = Field(None, title='Url')


class TagType(Enum):
    dietary = 'dietary'
    lifestyle = 'lifestyle'
    certification = 'certification'
    allergen = 'allergen'


class CategoriesResponse(BaseModel):
    categories: list[CategoryEntry] = Field(..., title='Categories')


class CoverageCountry(BaseModel):
    country_code: constr(pattern=r'^[A-Z]{2}$', min_length=2, max_length=2) = Field(
        ..., title='Country Code'
    )
    retailer_list: list[CoverageRetailer] | None = Field(
        [], title='Retailer List', validate_default=True
    )


class CoverageResponse(BaseModel):
    countries: list[CoverageCountry] = Field(..., title='Countries')
    generated_at: str = Field(..., title='Generated At')


class FacetCount(BaseModel):
    counts: list[FacetValueCount] = Field(..., title='Counts')
    field: str = Field(..., title='Field')


class SearchResponse(BaseModel):
    facets: list[FacetCount] = Field(..., title='Facets')
    found: int = Field(..., title='Found')
    hits: list[SearchHit] = Field(..., title='Hits')
    page: int = Field(..., title='Page')
    page_size: int = Field(..., title='Page Size')
    query: str = Field(..., title='Query')


class TagEntry(BaseModel):
    name: str = Field(..., title='Name')
    slug: str = Field(..., title='Slug')
    type: TagType


class TagsResponse(BaseModel):
    tags: list[TagEntry] = Field(..., title='Tags')
